name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint
      
      - name: Run tests
        run: npm test
      
      - name: Build for production
        run: npm run build
        env:
          VITE_API_BASE: ${{ secrets.PRODUCTION_API_BASE }}
      
      - name: Deploy to Production
        run: echo "Add your production deployment command here"
        # Example for Vercel: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
