name: Deploy to Staging

on:
  push:
    branches: [staging]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter (if exists)
        run: npm run lint || echo "No lint script found, skipping..."
        continue-on-error: true
      
      - name: Run tests (if exists)
        run: npm test || echo "No test script found, skipping..."
        continue-on-error: true
      
      - name: Build for staging
        run: npm run build
        env:
          VITE_API_BASE: ${{ secrets.STAGING_API_BASE }}
